version: '3.1'
services:
  next-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    restart: unless-stopped
    # command: "./src/bash/wait-for-it.sh db:27017 -- npm run dev"
